### ISSUE TITLE
camera-imu calibration

### ISSUE THREAD

**Issue by maulanaazhari** [tii-racing/drone-racing-dataset#4]
Hi! thanks for open-sourcing the dataset.

Is there any chance you can provide the IMU calibration and camera extrinsics relative to the IMU? both following the kalibr format (https://github.com/ethz-asl/kalibr).

Thank you!

**Comment by MichaelBosello** [comment]
Thank you for your interest in our dataset.

Unfortunately, performing the camera-IMU calibration is not straightforward as the sensors are not hardware synchronized, and at the time we recorded the dataset, it was not our priority. We thus don't have the data needed to perform such calibration with the exact same drone used in the dataset.

Nevertheless, you can find the file [drone_to_camera.json](https://github.com/tii-racing/drone-racing-dataset/blob/main/camera_calibration/drone_to_camera.json) which has been reported to be a good approximation of the drone-to-camera transformation.
`drone_to_camera.json - Drone to camera in JSON format. Translation was measured by MoCap, rotation is an estimation, and includes the FLU to RDF conversion.`

**Comment by maulanaazhari** [comment]
Thanks for the response.

I tried to reproject the gate corners into the camera optical frame by using:

1. the odometry to transform the gate from the "map" frame to "drone" frame
2. then use the `drone_to_camera.json` to transform from "drone" frame to "camera" frame. 
3. Then use the opencv `projectPoints` function to have the gate in the camera optical frame.

However, the result is not good. I guess due to the rotation just only an estimation (?)
![image](https://github.com/user-attachments/assets/937f11df-aa46-4305-8ea9-4b3fabfb4bb7)

When I adjusted drone to camera rotation to `q_xyzw = [-0.3641869, 0.3641869, -0.6061088, 0.6061088]` the result is better.
![image](https://github.com/user-attachments/assets/b7ff90bd-1a6a-4c65-bf67-402fec312636)

my question is: how did you verify that the `drone_to_camera.json` is a good enough approximation? since it doesn't give a good result in my case. However, there is also a chance that  I have a bug in my code so the result of `drone_to_camera.json` is not good

**Comment by MichaelBosello** [comment]
Which flight and image number are you using in the example? Can you share the code you are using for the reprojection to help us understand where the problem is? Thanks

**Comment by MichaelBosello** [comment]
Close as inactive

**Comment by maulanaazhari** [comment]
Sorry for the delayed response. I was using **piloted 01p-ellipse flight**, however the `drone_to_camera.json` seems to be valid when I used it for the **autonomous 01a-ellipse flight**. I suppose the `drone_to_camera.json` is for autonomous flights only? I haven't checked all of the flights.

**Comment by MichaelBosello** [comment]
You are right, for the piloted flights we used 30 degrees camera angle (for both ellipse and lemniscate), which was reported in the paper but not in the [drone_to_camera.json](https://github.com/tii-racing/drone-racing-dataset/blob/main/camera_calibration/drone_to_camera.json) due to an oversight. I added a "piloted" entry with commit 4e50a5ab8ef1e331d70d239eb5fb9adf6abbae4d. Thanks for pointing this out
