### ISSUE TITLE
piloted zipfile is corrupted

### ISSUE THREAD

**Issue by ChanJoon** [tii-racing/drone-racing-dataset#5]
Thank you for your work.

As I followed the instructions in Release or ran `data_downloader.sh`, the process fails to unzip piloted.zip

To reproduce,
```bash
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk01
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk02
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk03
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk04
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk05
wget https://github.com/Drone-Racing/drone-racing-dataset/releases/download/v2.0.0/piloted_zipchunk06
cat piloted_zipchunk* > piloted.zip
unzip piloted.zip
```

Then the results shows
```bash
Archive:  piloted.zip
fatal error: read failure while seeking for End-of-centdir-64 signature.
  This zipfile is corrupt.
unzip:  cannot find zipfile directory in one of piloted.zip or
        piloted.zip.zip, and cannot find piloted.zip.ZIP, period
```

I tried to repair the zipfile as follows:
```bash
❯ zip -FF piloted.zip --out fixed.zip
Fix archive (-FF) - salvage what can
 Found end record (EOCDR) - says expect single disk archive
Scanning for entries...
 copying: piloted/  (0 bytes)
 copying: piloted/flight-01p-ellipse/  (0 bytes)
 copying: piloted/flight-01p-ellipse/camera_flight-01p-ellipse.zip 
	zip warning: no end of stream entry found: piloted/flight-01p-ellipse/camera_flight-01p-ellipse.zip
	zip warning: rewinding and scanning for later entries
```

How to fix it? Or could you please look into the released zipchunks and update them?

Thanks!

**Comment by MichaelBosello** [comment]
Thank you for the interest in our dataset.

We cannot reproduce the problem at the moment.
Which OS are you using? Did you try downloading the zip chunks again?

**Comment by ChanJoon** [comment]
> Thank you for the interest in our dataset.
> 
> We cannot reproduce the problem at the moment. Which OS are you using? Did you try downloading the zip chunks again?

Thank you for your quick response.

I’m currently using Ubuntu 20.04. I will manually download the zip chunks from the GitHub website and let you know the results.

**Comment by ChanJoon** [comment]
Sorry for late response.

I brought more detailed inspection with manually downloaded zip chunks. (from the Release)

![image](https://github.com/user-attachments/assets/4c456c5a-9f76-4ac4-8878-67ef03ac8e98)

As you can see in the image, **piloted_zipchunk01** shows a `Zip archive` type while others are `Binary` types.

Tried to open the piloted_zipchunk01 also failed. I think it's corrupted.

So could you please check those files again?

Or you can send me your file via my email (chanjoon.park@kaist.ac.kr). Then I will check on my Ubuntu 20.04.

Thanks!

**Comment by ChanJoon** [comment]
I solved. There was a no problem in your release.

```bash
cat piloted_zipchunk01 piloted_zipchunk02 piloted_zipchunk03 piloted_zipchunk04 piloted_zipchunk05 piloted_zipchunk06 > combined.zip # For specify the first header
cat piloted_zipchunk0* > piloted.zip
unzip piloted.zip # or combined.zip
```

Maybe the problem was due to my filesystem or `wget`. Manually downloading the files worked.
(though I’m not sure why my previous shell script attempts failed.)

**Comment by sbahnam** [comment]
I had the same problem for autonomous flight zip. Manually downloading them and unzipping them afterwards works for me too
