### ISSUE TITLE
What is the coordinate system for accelerations?

### ISSUE THREAD

**Issue by shisoft** [tii-racing/drone-racing-dataset#6]
From your data, the `accel_z` starts with a positive gravity, which is the opposite of the direction to the ground. In my use case, MAVlink is in the NED body frame, and its acceleration at the z-axis starts with negative gravity. 

I am having trouble converting this dataset for my case. What coordinate system is it using?

Thank you

**Comment by shisoft** [comment]
Ah, I see your paper at https://arxiv.org/pdf/2311.02667. 
It seems like I need to invert `z` and `y` axis to get NED body frame.

**Comment by MichaelBosello** [comment]
We used ENU (east, north, up) coordinates, i.e., X: forward; Y: left; Z: up. To convert to NED, you indeed need to invert Y and Z.
